/**
 * Motion config — HyperFrames-based generation.
 *
 * Each motion is a unique HTML composition generated by Gemini, rendered to MP4
 * by HyperFrames (via Tauri sidecar). The user picks a style preset + free-form
 * intent; Gemini generates the HTML; HyperFrames renders it.
 *
 * Compared to the old Remotion templates approach: no fixed templates. Each motion
 * is contextual to the specific block content, while staying within the visual
 * grammar of the chosen style preset.
 */

import type { StylePresetId } from './motionStylePresets';

// overlay: motion blends over avatar (screen blend)
// replace: motion fills the full frame
// split-bottom: avatar top half, motion bottom half
// split-top: motion top half, avatar bottom half
export type MotionLayer = 'overlay' | 'replace' | 'split-bottom' | 'split-top';

export type MotionRenderStatus = 'draft' | 'generating' | 'ready' | 'rendering' | 'error';

export interface MotionConfig {
  /** Unique id (used as composition-id and as filename in cache). */
  id: string;
  /** Style preset (palette, typography, motion grammar). */
  presetId: StylePresetId;
  /** Layer relative to avatar / b-roll. */
  layer: MotionLayer;
  /** User-provided intent: what the motion should illustrate. */
  intent: string;
  /** Primary text shown in the motion (auto-derived from block, user can edit). */
  text: string;
  /** Optional secondary text. */
  secondaryText?: string;
  /** Optional number for count-up style motions. */
  number?: number;
  /** Duration in seconds. */
  durationSec: number;
  /** HTML composition body (generated by Gemini). Empty until first generation. */
  html: string;
  /** Absolute path of the rendered MP4 (set by Rust after `render_motion`). */
  videoPath?: string;
  /** Latest render status. */
  status: MotionRenderStatus;
  /** Last error message, if any. */
  errorMessage?: string;
  /** When the motion config was created. */
  createdAt: number;
  /** When the HTML was last (re)generated. */
  generatedAt?: number;
  /** When the MP4 was last rendered. */
  renderedAt?: number;
}

export const newMotionId = (): string =>
  `mot_${Math.random().toString(36).slice(2, 10)}_${Date.now().toString(36)}`;

export const motionNeedsRender = (m: MotionConfig): boolean =>
  m.status === 'draft' || (!!m.html && !m.videoPath) || (!!m.generatedAt && !!m.renderedAt && m.generatedAt > m.renderedAt);

/** Derive a short headline from the block text (used as the motion's primary text). */
const deriveHeadline = (text: string): string => {
  const t = text.trim();
  if (t.length <= 60) return t;
  const sentence = t.split(/[.!?]\s/)[0];
  if (sentence.length <= 60) return sentence;
  return sentence.slice(0, 60).split(' ').slice(0, -1).join(' ') + '…';
};

/** Build a fresh MotionConfig with sensible defaults inferred from the block. */
export const createMotionFromBlock = (block: { text: string; start: number; end: number; kind?: 'avatar' | 'broll' }): MotionConfig => {
  const blockDur = Math.max(2, Math.min(8, Math.round(block.end - block.start)));
  // Avatar blocks → split-bottom (50/50 with the avatar). B-roll blocks → replace
  // (B-roll is full-frame anyway; motion takes over the whole frame).
  const layer: MotionLayer = block.kind === 'broll' ? 'replace' : 'split-bottom';
  return {
    id: newMotionId(),
    presetId: 'glass-tech',
    layer,
    intent: '',
    text: deriveHeadline(block.text),
    durationSec: blockDur || 4,
    html: '',
    status: 'draft',
    createdAt: Date.now(),
  };
};
