/**
 * Motion config — HyperFrames-based generation.
 *
 * Each motion is a unique HTML composition generated by Gemini, rendered to MP4
 * by HyperFrames (via Tauri sidecar). The user picks a style preset + free-form
 * intent; Gemini generates the HTML; HyperFrames renders it.
 *
 * Compared to the old Remotion templates approach: no fixed templates. Each motion
 * is contextual to the specific block content, while staying within the visual
 * grammar of the chosen style preset.
 */

import type { StylePresetId } from './motionStylePresets';

// overlay: motion blends over avatar (screen blend)
// replace: motion fills the full frame
// split-bottom: avatar top half, motion bottom half
// split-top: motion top half, avatar bottom half
export type MotionLayer = 'overlay' | 'replace' | 'split-bottom' | 'split-top';

export type MotionRenderStatus = 'draft' | 'generating' | 'ready' | 'rendering' | 'error';

export interface MotionConfig {
  /** Unique id (used as composition-id and as filename in cache). */
  id: string;
  /** Style preset (palette, typography, motion grammar). */
  presetId: StylePresetId;
  /** Layer relative to avatar / b-roll. */
  layer: MotionLayer;
  /** User-provided intent: what the motion should illustrate. */
  intent: string;
  /** Primary text shown in the motion (auto-derived from block, user can edit). */
  text: string;
  /** Optional secondary text. */
  secondaryText?: string;
  /** Optional number for count-up style motions. */
  number?: number;
  /** Duration in seconds. */
  durationSec: number;
  /** HTML composition body (generated by Gemini). Empty until first generation. */
  html: string;
  /** Absolute path of the rendered MP4 (set by Rust after `render_motion`). */
  videoPath?: string;
  /** Latest render status. */
  status: MotionRenderStatus;
  /** Last error message, if any. */
  errorMessage?: string;
  /** When the motion config was created. */
  createdAt: number;
  /** When the HTML was last (re)generated. */
  generatedAt?: number;
  /** When the MP4 was last rendered. */
  renderedAt?: number;
  /** Canvas aspect ratio used when generating this motion. '4:5' for carousel, '9:16' (default) for reels. */
  canvasAspect?: '9:16' | '4:5';
  /**
   * Ordered snapshot of the user-attached assets at the moment this motion's
   * HTML was generated. Compared at regeneration time against
   * `block.attachedAssets` to detect a stale state — different length OR any
   * different path at the same index marks the motion as stale.
   * undefined = motion was generated without any pinned assets.
   */
  assetSnapshots?: Array<{
    path: string;
    name: string;
  }>;
  /** @deprecated legacy single-asset snapshot. Hydration migrates it into assetSnapshots. */
  assetSnapshot?: {
    path: string;
    name: string;
  };
}

export const newMotionId = (): string =>
  `mot_${Math.random().toString(36).slice(2, 10)}_${Date.now().toString(36)}`;

export const motionNeedsRender = (m: MotionConfig): boolean =>
  m.status === 'draft' || (!!m.html && !m.videoPath) || (!!m.generatedAt && !!m.renderedAt && m.generatedAt > m.renderedAt);

/**
 * Compare a motion's snapshot of attached assets (taken at generation time)
 * against the block's current carousel. Returns true when the motion's HTML
 * no longer reflects what the user wants — different length, different order,
 * or a swapped path.
 *
 * Accepts the legacy single-asset shape (motion.assetSnapshot, block has
 * attachedAsset) so old motions still flag correctly until regenerated.
 */
export const isMotionAssetsStale = (
  motion: { assetSnapshots?: Array<{ path: string }>; assetSnapshot?: { path: string }; html?: string } | undefined,
  currentAssets: Array<{ path: string }> | undefined,
): boolean => {
  if (!motion?.html) return false; // never generated → not stale
  // Read from the new field, falling back to legacy.
  const snaps = motion.assetSnapshots ?? (motion.assetSnapshot ? [motion.assetSnapshot] : []);
  const current = currentAssets ?? [];
  if (snaps.length !== current.length) return true;
  for (let i = 0; i < snaps.length; i++) {
    if (snaps[i].path !== current[i].path) return true;
  }
  return false;
};

/** Derive a short headline from the block text (used as the motion's primary text). */
const deriveHeadline = (text: string): string => {
  const t = text.trim();
  if (t.length <= 60) return t;
  const sentence = t.split(/[.!?]\s/)[0];
  if (sentence.length <= 60) return sentence;
  return sentence.slice(0, 60).split(' ').slice(0, -1).join(' ') + '…';
};

/** Build a fresh MotionConfig with sensible defaults inferred from the block. */
export const createMotionFromBlock = (block: { text: string; start: number; end: number; kind?: 'avatar' | 'broll' }): MotionConfig => {
  const blockDur = Math.max(2, Math.min(8, Math.round(block.end - block.start)));
  // Avatar blocks → split-bottom (50/50 with the avatar). B-roll blocks → replace
  // (B-roll is full-frame anyway; motion takes over the whole frame).
  const layer: MotionLayer = block.kind === 'broll' ? 'replace' : 'split-bottom';
  return {
    id: newMotionId(),
    presetId: 'glass-tech',
    layer,
    intent: '',
    text: deriveHeadline(block.text),
    durationSec: blockDur || 4,
    html: '',
    status: 'draft',
    createdAt: Date.now(),
  };
};
