// React hook that drives the embedded chat. Owns the message list, listens
// to Tauri events from claude_subprocess.rs, and surfaces a tiny API
// (send, cancel, approve, clear, setModel, send-with-attachments) to
// <AgentPanel>.
//
// Event flow:
//   agent://message         → parsed for tool_use, tool_result, full text
//   agent://stream-delta    → token-by-token text fragments (we accumulate
//                             these into a single assistant ChatMessage
//                             keyed by the Claude message id)
//   agent://approval-request → renders an ApprovalCard inline
//   agent://result          → end-of-turn marker (clears busy)
//   agent://run-ended       → subprocess died (clears busy as backup)
//   agent://error           → shows red error row
//
// Tool progress UX:
//   We turn `tool_use` events into human-readable pills via toolLabels.ts.
//   When the matching `tool_result` arrives, we flip the pill from "doing"
//   to "done" by toolCallId, optionally extracting context (block count
//   etc.) for the past-tense label.

import { useCallback, useEffect, useRef, useState } from 'react';
import { invoke } from '@tauri-apps/api/core';
import { listen, type UnlistenFn } from '@tauri-apps/api/event';
import type { Locale } from './i18n';
import { labelFor } from './toolLabels';
import { resolveTextProvider, resolveMotionProvider } from './agentPrefs';
import { activeProfileWithSpeechStyle, buildVoicePromptSection } from '../reelsStudio/voiceProfile';

export type ChatRole = 'user' | 'assistant' | 'system' | 'tool' | 'error';

export type ToolStatus = 'doing' | 'done' | 'error';

export interface AttachmentMeta {
  /** UUID we make up locally so the UI can key the preview row. */
  id: string;
  kind: 'image' | 'video';
  /** Filesystem name for the chip label. */
  name: string;
  /** Object URL for live preview while attached. Revoked on remove/send. */
  previewUrl: string;
  /** Original File (for base64 conversion or path retrieval). */
  file: File;
  /** Bytes — informational. */
  size: number;
}

/// Pre-flight setup card. Surfaced in the chat right before a video URL
/// import runs, so the user can dial duration/tone/focus once instead of
/// the typical 3-4 cycles of "ok, more detail / shorter / different
/// tone". The card resolves a local Promise (not a Tauri command) — the
/// bridge handler awaits it before kicking off yt-dlp.
export interface SetupPrompt {
  setupId: string;
  title?: string;
  subtitle?: string;
  resolved?: 'submitted' | 'skipped' | 'cancelled';
}

/// Preview of a generated script before it overwrites the project. Lives
/// in a chat message; the user reviews + clicks Apply or Discard.
export interface DraftPreview {
  /** Stable id used by Apply/Discard handlers. */
  draftId: string;
  /** Friendly label for the source ('reel @user/abc', 'artigo X', etc). */
  source: string;
  /** Canonical URL the draft was generated from (when applicable). Used to
   *  invalidate older drafts of the same source — re-importing the same
   *  reel marks previous drafts as 'superseded' so the user can't apply a
   *  stale version by accident. */
  sourceUrl?: string;
  /** Where this draft will land if approved. 'reel' = ScriptBlock list,
   *  'carousel' = same but with carousel aspect. */
  kind: 'reel' | 'carousel';
  /** Lightweight block list for the preview UI (no full ScriptBlock — we
   *  keep the rich version in a separate ref keyed by draftId). */
  blocks: Array<{ kind: 'avatar' | 'broll'; text: string }>;
  /** Optional short metadata to show under the title ("PT-BR · 7 blocos"). */
  meta?: string;
  /** Final state of the card.
   *  - 'applied'    → user clicked Apply, blocks pushed to the project
   *  - 'discarded'  → user dismissed
   *  - 'superseded' → a newer draft of the same sourceUrl arrived */
  resolved?: 'applied' | 'discarded' | 'superseded';
}

export interface ChatMessage {
  id: string;
  role: ChatRole;
  /** Body text. For assistant streaming this grows over time. */
  text: string;
  /** Tool pill data. Only set when role === 'tool'. */
  toolName?: string;
  toolCallId?: string;
  toolStatus?: ToolStatus;
  /** Vars to render into the done-label (e.g. block count). */
  toolDoneVars?: Record<string, string | number>;
  /** Raw result payload for the debug <details>. */
  toolResultRaw?: unknown;
  /** Approval card props (only set when this row is an approval prompt). */
  approvalId?: string;
  toolInput?: unknown;
  resolved?: 'allow' | 'deny';
  /** Picker card props (only set when this row is a visual picker). */
  pickerId?: string;
  pickerKind?: string;
  pickerTitle?: string;
  pickerSubtitle?: string;
  pickerOptions?: Array<{
    id: string;
    label: string;
    description?: string;
    thumbnail?: string;
    badge?: string;
  }>;
  pickerChoice?: string;
  /** Draft preview card (script generated by an import, awaiting apply). */
  draft?: DraftPreview;
  /** Setup card (pre-flight Q&A before a video import runs). */
  setup?: SetupPrompt;
  /** Whether this row is still accumulating tokens. */
  streaming?: boolean;
  /** Optional: image/video chips to display under a user message. */
  attachments?: Array<{ kind: 'image' | 'video'; name: string; previewUrl?: string }>;
  /** Optional: AI generated thumbnail data URL (base64 image) and its filename */
  thumbnailDataUrl?: string;
  thumbnailFilename?: string;
}

interface MessageEnvelope {
  run_id: string;
  payload: {
    type?: string;
    subtype?: string;
    message?: {
      role?: string;
      content?: Array<
        | { type: 'text'; text: string }
        | { type: 'tool_use'; id: string; name: string; input: unknown }
        | { type: 'tool_result'; tool_use_id: string; content: unknown; is_error?: boolean }
      >;
    };
    [k: string]: unknown;
  };
}

interface StreamDeltaEnvelope {
  run_id: string;
  payload: {
    type: 'stream_event';
    event: {
      type: string;
      index?: number;
      message?: { id?: string };
      content_block?: { type?: string; text?: string };
      delta?: { type?: string; text?: string; partial_json?: string };
    };
  };
}

interface ResultEnvelope {
  run_id: string;
  payload: {
    type: 'result';
    subtype?: string;
    duration_ms?: number;
    total_cost_usd?: number;
    is_error?: boolean;
    result?: string;
    [k: string]: unknown;
  };
}

interface ApprovalRequestEvent {
  approval_id: string;
  tool_name: string;
  tool_input: unknown;
}

interface PickerRequestEvent {
  picker_id: string;
  kind: string;
  title: string;
  subtitle?: string;
  options: Array<{
    id: string;
    label: string;
    description?: string;
    thumbnail?: string;
    badge?: string;
  }>;
}

interface ErrorEvent {
  run_id?: string;
  message: string;
  raw?: string;
  source?: string;
}

function uid(): string {
  return Math.random().toString(36).slice(2, 11);
}

// Claude Code CLI accepts the short alias ("sonnet" / "opus" / "haiku") OR
// the full model id. Aliases are stable across model generations.
export type ClaudeModel = 'sonnet' | 'opus' | 'haiku';

const MODEL_STORAGE_KEY = 'reels.agent.model';

function loadStoredModel(): ClaudeModel {
  const raw = localStorage.getItem(MODEL_STORAGE_KEY);
  if (raw === 'opus' || raw === 'haiku') return raw;
  return 'sonnet';
}

// Cap on attachment size that gets uploaded to a temp file for the agent.
// Mirrors the limit enforced by the Rust `agent_write_attachment_temp`
// command — keeping them in sync avoids confusing error messages.
const MAX_ATTACHMENT_BYTES = 50 * 1024 * 1024;

async function fileToBytes(file: File): Promise<Uint8Array> {
  const buf = await file.arrayBuffer();
  return new Uint8Array(buf);
}

/// Persist an attachment to an OS temp file (via the Rust side) and return
/// its absolute path. The agent prompt references the file by path instead
/// of inlining base64 — which would blow past the Claude context window for
/// anything beyond a small thumbnail.
async function persistAttachmentTemp(att: AttachmentMeta): Promise<string> {
  const bytes = await fileToBytes(att.file);
  return await invoke<string>('agent_write_attachment_temp', {
    filename: att.name,
    bytes: Array.from(bytes),
  });
}

/// Build the augmented prompt that goes to Claude when attachments are
/// present. Images and videos are saved to OS temp files and referenced by
/// absolute path — Claude Code CLI can read them via the `@<path>` syntax
/// (for images it routes them through Vision automatically). We avoid
/// inlining base64 because (a) it explodes ARG_MAX when prompts are passed
/// as CLI args and (b) it consumes the Claude context window character-by-
/// character even though the bytes are opaque to the model.
async function buildPromptWithAttachments(
  prompt: string,
  attachments: AttachmentMeta[],
): Promise<string> {
  if (attachments.length === 0) return prompt;
  const chunks: string[] = [prompt];
  for (const att of attachments) {
    if (att.size > MAX_ATTACHMENT_BYTES) {
      chunks.push(`\n[${att.name} excedeu 50MB — anexada apenas como referência de nome.]`);
      continue;
    }
    try {
      const path = await persistAttachmentTemp(att);
      if (att.kind === 'image') {
        // Claude Code CLI's `@<path>` syntax auto-loads the file. For images
        // that means Vision processes it as a real image block — no token
        // bloat from base64 in the prompt body.
        chunks.push(`\n<image filename="${att.name}">@${path}</image>`);
      } else {
        // Videos pass as a path the agent can hand to MCP tools
        // (add_broll_to_block, attach_asset_from_path, etc.). Claude itself
        // can't view video frames yet.
        chunks.push(`\n<video_path filename="${att.name}">${path}</video_path>`);
      }
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      chunks.push(`\n[Falhou ao anexar ${att.name}: ${msg}]`);
    }
  }
  return chunks.join('\n');
}

// Tiny UUID v4 — same shape as Rust side, just for session identifiers.
function uuidV4(): string {
  // Use crypto.randomUUID when available (modern browsers / Tauri webview).
  if (typeof crypto !== 'undefined' && 'randomUUID' in crypto) {
    try { return (crypto as Crypto & { randomUUID(): string }).randomUUID(); } catch { /* fall through */ }
  }
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, c => {
    const r = (Math.random() * 16) | 0;
    return (c === 'x' ? r : (r & 0x3) | 0x8).toString(16);
  });
}

function sessionStorageKey(projectKey: string): string {
  return `reels.agent.session.${projectKey || '_default'}`;
}

// CLI-internal tools we don't want to expose as user-facing pills.
// `ToolSearch` is the Claude Code runtime's mechanism to lazy-load tool
// schemas when many tools are registered — it's plumbing, not work the
// user asked for. Suppressing it keeps the chat clean during multi-step
// MCP workflows.
const HIDDEN_TOOL_SENTINEL = '__hidden_tool__';
const HIDDEN_TOOLS = new Set<string>(['ToolSearch']);

function isHiddenTool(name: string): boolean {
  return HIDDEN_TOOLS.has(name);
}

function loadSessionFor(projectKey: string): string | null {
  try {
    return localStorage.getItem(sessionStorageKey(projectKey));
  } catch {
    return null;
  }
}

function saveSessionFor(projectKey: string, sessionId: string): void {
  try {
    localStorage.setItem(sessionStorageKey(projectKey), sessionId);
  } catch { /* ignore */ }
}

function deleteSessionFor(projectKey: string): void {
  try {
    localStorage.removeItem(sessionStorageKey(projectKey));
  } catch { /* ignore */ }
}

export function useAgentChat(locale: Locale, projectKey: string = '_default') {
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [busy, setBusy] = useState(false);
  /** ChatGPT-style "is it stuck?" indicator. True when no stdout chunk
   *  has arrived for STALL_SECS (Rust-side watchdog, default 30s).
   *  Cleared automatically when a chunk arrives, or when the run ends. */
  const [stale, setStale] = useState(false);
  // Session id is scoped to the current project. When the user switches
  // projects (projectKey changes), we reload the matching saved id so the
  // agent picks up the prior conversation. The actual conversation history
  // lives on the Claude Code side at ~/.claude/projects/<cwd>/<sid>.jsonl;
  // we just track the id locally so we can pass `--session-id` consistently.
  const [sessionId, setSessionId] = useState<string | null>(() => loadSessionFor(projectKey));
  const [model, setModelState] = useState<ClaudeModel>(loadStoredModel);

  // Mirror projectKey into a ref so the long-lived event listeners (installed
  // once in a useEffect with stable deps) can always read the CURRENT key
  // when an event fires — without re-installing the listeners on every
  // project switch (which would duplicate them).
  const projectKeyRef = useRef(projectKey);
  useEffect(() => { projectKeyRef.current = projectKey; }, [projectKey]);

  // Reload session when project changes.
  useEffect(() => {
    setSessionId(loadSessionFor(projectKey));
    // Don't wipe message list — those are React-only and the user might
    // have just toggled the panel; the displayed history belongs to the
    // panel, the persisted memory belongs to the agent.
  }, [projectKey]);

  const setModel = useCallback((next: ClaudeModel) => {
    setModelState(next);
    localStorage.setItem(MODEL_STORAGE_KEY, next);
  }, []);

  const messagesRef = useRef(messages);
  messagesRef.current = messages;

  // Stream-accumulator state. Maps an assistant Claude message id → the
  // local ChatMessage id we're appending tokens into. Held in a ref so the
  // listener closures see fresh values without re-subscribing.
  const streamMapRef = useRef<Map<string, string>>(new Map());
  // Maps tool_use_id → local ChatMessage id (for tool pills).
  const toolMapRef = useRef<Map<string, string>>(new Map());

  const append = useCallback((msg: Omit<ChatMessage, 'id'> & { id?: string }) => {
    const id = msg.id ?? uid();
    setMessages(prev => [...prev, { ...msg, id }]);
    return id;
  }, []);

  const patch = useCallback((id: string, updater: Partial<ChatMessage> | ((m: ChatMessage) => Partial<ChatMessage>)) => {
    setMessages(prev =>
      prev.map(m => {
        if (m.id !== id) return m;
        const u = typeof updater === 'function' ? updater(m) : updater;
        return { ...m, ...u };
      }),
    );
  }, []);

  // Wire Tauri events once.
  useEffect(() => {
    // Async-cleanup-safe pattern. React.StrictMode (dev) runs each effect
    // twice. The cleanup of the first pass fires *while setup() is still
    // awaiting listen(...)*, so `unlisteners` is empty and the second
    // pass installs duplicate listeners on top. That's the bug that made
    // every approval card / picker / tool pill render twice. Fix: guard
    // the whole setup with a `cancelled` flag and inline-unregister any
    // listener whose `listen(...)` resolves after the effect tore down.
    let cancelled = false;
    const unlisteners: UnlistenFn[] = [];
    const installed = async (promise: Promise<UnlistenFn>): Promise<void> => {
      const unlisten = await promise;
      if (cancelled) {
        // Effect was torn down before this listen() resolved (StrictMode
        // double-mount in dev). Unregister inline so we don't end up with
        // a duplicate listener leaking into the next mount.
        unlisten();
        return;
      }
      unlisteners.push(unlisten);
    };

    const setup = async () => {
      // Full-message envelopes: surface tool_use as pills, tool_result as
      // pill state updates, and any final assistant text the CLI sends as
      // a non-streamed message.
      await installed(listen<MessageEnvelope>('agent://message', e => {
          const { payload } = e.payload;
          const role = payload.message?.role;
          const content = payload.message?.content ?? [];

          for (const part of content) {
            if (part.type === 'text' && part.text.trim()) {
              const cid = payload.message && (payload.message as { id?: string }).id;
              const streamedLocalId = cid ? streamMapRef.current.get(cid) : undefined;

              if (role === 'assistant') {
                if (streamedLocalId) {
                  // The stream already created a bubble for this Claude
                  // message id. Replace its text with the canonical final
                  // version (handles the case where the stream truncated
                  // for any reason — never duplicate).
                  setMessages(prev =>
                    prev.map(m =>
                      m.id === streamedLocalId
                        ? { ...m, text: part.text, streaming: false }
                        : m,
                    ),
                  );
                } else {
                  // No prior streaming bubble — straight append.
                  append({ role: 'assistant', text: part.text });
                }
              } else if (role === 'user') {
                // Silently ignore synthetic user echos (CLI emits these
                // when relaying tool results). We render those via the
                // tool pill flow instead.
              }
            } else if (part.type === 'tool_use') {
              // Hide CLI plumbing tools (`ToolSearch` lazy-loads tool schemas;
              // it's not meaningful work to surface to the user). We still
              // need to track the id so the matching `tool_result` doesn't
              // become an orphan — use a sentinel that the tool_result branch
              // recognises and silently consumes.
              if (isHiddenTool(part.name)) {
                toolMapRef.current.set(part.id, HIDDEN_TOOL_SENTINEL);
                continue;
              }
              const labelMeta = labelFor(part.name);
              const localId = append({
                role: 'tool',
                text: '',
                toolName: part.name,
                toolCallId: part.id,
                toolStatus: 'doing',
                toolResultRaw: part.input,
              });
              toolMapRef.current.set(part.id, localId);
              // Reference labelMeta so it's not stripped by tree-shaking.
              void labelMeta;
            } else if (part.type === 'tool_result') {
              const localId = toolMapRef.current.get(part.tool_use_id);
              if (!localId) continue;
              if (localId === HIDDEN_TOOL_SENTINEL) {
                toolMapRef.current.delete(part.tool_use_id);
                continue;
              }
              const isError = !!part.is_error;
              setMessages(prev =>
                prev.map(m => {
                  if (m.id !== localId) return m;
                  const label = labelFor(m.toolName ?? '');
                  const vars = label.extractVars?.(part.content);
                  return {
                    ...m,
                    toolStatus: isError ? 'error' : 'done',
                    toolDoneVars: vars,
                    toolResultRaw: part.content,
                  };
                }),
              );
              toolMapRef.current.delete(part.tool_use_id);
            }
          }
        }),
      );

      // Token-by-token streaming.
      await installed(listen<StreamDeltaEnvelope>('agent://stream-delta', e => {
          const event = e.payload.payload?.event;
          if (!event) return;

          switch (event.type) {
            case 'message_start': {
              const cid = event.message?.id;
              if (!cid) return;
              if (streamMapRef.current.has(cid)) return;
              const localId = append({
                role: 'assistant',
                text: '',
                streaming: true,
              });
              streamMapRef.current.set(cid, localId);
              return;
            }
            case 'content_block_delta': {
              if (event.delta?.type !== 'text_delta') return;
              // Find the most recent streaming bubble. We don't reliably
              // get the message id on every delta, so fall back to the
              // newest streamMap entry.
              const cid = Array.from(streamMapRef.current.keys()).pop();
              if (!cid) return;
              const localId = streamMapRef.current.get(cid);
              if (!localId) return;
              const text = event.delta.text ?? '';
              setMessages(prev =>
                prev.map(m => (m.id === localId ? { ...m, text: m.text + text } : m)),
              );
              return;
            }
            case 'message_stop': {
              // Mark all streaming bubbles done (only one expected per turn).
              // Keep streamMap populated so the matching `agent://message`
              // envelope that follows is recognised as "already rendered"
              // and skipped — otherwise the same text gets appended twice.
              // Also drop any assistant bubble that received zero text deltas:
              // happens when the model goes straight to a tool_use without
              // narrating, and would otherwise render as an empty ghost bubble.
              setMessages(prev =>
                prev
                  .map(m => (m.streaming ? { ...m, streaming: false } : m))
                  .filter(m => !(m.role === 'assistant' && !m.text.trim())),
              );
              return;
            }
            default:
              return;
          }
        }),
      );

      await installed(listen<ResultEnvelope>('agent://result', e => {
          const { payload } = e.payload;
          setBusy(false);
          // Make sure no bubble is left "streaming" if message_stop didn't fire.
          setMessages(prev => prev.map(m => (m.streaming ? { ...m, streaming: false } : m)));
          if (payload.is_error) {
            append({ role: 'error', text: payload.result ?? 'Erro desconhecido' });
          }
        }));

      await installed(listen<ErrorEvent>('agent://error', e => {
        setBusy(false);
        const msg = e.payload.message;
        // Detect context-window overflow — usually means a previous turn
        // baked something huge into the session (image base64 dumped inline
        // before the temp-file fix). Resuming carries that payload forward
        // forever, so the only way out is a fresh session. Reset locally
        // and tell the user — without this they're stuck re-typing into
        // a poisoned chat with no obvious way out.
        if (/prompt is too long|context.*too long|context.*window|too many tokens/i.test(msg)) {
          setSessionId(null);
          deleteSessionFor(projectKeyRef.current);
          append({
            role: 'error',
            text: `${msg}\n\nA sessão anterior ficou pesada demais. Iniciei uma nova — pode reenviar.`,
          });
        } else {
          append({ role: 'error', text: msg });
        }
      }));

      await installed(listen<{ run_id: string; exit_code: number | null; cancelled?: boolean }>(
        'agent://run-ended',
        () => {
          setBusy(false);
          setStale(false);
          setMessages(prev =>
            prev
              .map(m => (m.streaming ? { ...m, streaming: false } : m))
              .filter(m => !(m.role === 'assistant' && !m.text.trim())),
          );
          streamMapRef.current.clear();
        },
      ));

      await installed(listen<{ run_id: string; silent_secs: number }>(
        'agent://stale-warning',
        () => setStale(true),
      ));

      await installed(listen<{ run_id: string }>(
        'agent://stale-cleared',
        () => setStale(false),
      ));

      await installed(listen<ApprovalRequestEvent>('agent://approval-request', e => {
        const { approval_id, tool_name, tool_input } = e.payload;
        append({
          role: 'system',
          text: '',
          toolName: tool_name,
          approvalId: approval_id,
          toolInput: tool_input,
        });
      }));

      await installed(listen<PickerRequestEvent>('agent://picker-request', e => {
        const { picker_id, kind, title, subtitle, options } = e.payload;
        append({
          role: 'system',
          text: '',
          pickerId: picker_id,
          pickerKind: kind,
          pickerTitle: title,
          pickerSubtitle: subtitle,
          pickerOptions: options,
        });
      }));
    };

    void setup();
    return () => {
      cancelled = true;
      for (const u of unlisteners) u();
    };
  }, [append, patch]);

  const send = useCallback(
    async (rawPrompt: string, attachments: AttachmentMeta[] = []) => {
      if ((!rawPrompt.trim() && attachments.length === 0) || busy) return;

      // Compose the visible chat row first (with attachment chips), then
      // build the augmented prompt that actually goes to Claude.
      append({
        role: 'user',
        text: rawPrompt,
        attachments: attachments.map(a => ({
          kind: a.kind,
          name: a.name,
          previewUrl: a.previewUrl,
        })),
      });
      setBusy(true);

      // Lazily mint a session id on first send so the agent keeps memory
      // across turns. The CLI requires `--session-id <uuid>` to *create* the
      // session, and `--resume <uuid>` to continue it — reusing `--session-id`
      // fails with "Session ID ... is already in use". We pass `resumeSession`
      // so the Rust side picks the right flag.
      let activeSession = sessionId;
      let resumeSession = true;
      if (!activeSession) {
        activeSession = uuidV4();
        setSessionId(activeSession);
        saveSessionFor(projectKey, activeSession);
        resumeSession = false;
      }

      try {
        const finalPrompt = await buildPromptWithAttachments(rawPrompt, attachments);
        // Resolve at send-time (not hook-mount) so toggling either provider
        // in Settings takes effect on the NEXT message without remounting.
        const textProvider = resolveTextProvider();
        const motionProvider = resolveMotionProvider();
        // Pre-build the voice profile prompt block on the React side using
        // the active profile. The Rust side appends it to the system
        // prompt only when text_provider === 'claude' (Gemini gets the
        // voice profile via the regenerateBlock/generateReelFromContent
        // services directly — different injection point).
        let voicePrompt: string | null = null;
        try {
          const profile = activeProfileWithSpeechStyle();
          if (profile) voicePrompt = buildVoicePromptSection(profile);
        } catch {
          /* voice profile module not initialized yet — skip */
        }
        await invoke<string>('agent_send', {
          prompt: finalPrompt,
          sessionId: activeSession,
          resumeSession,
          model,
          locale,
          textProvider,
          motionProvider,
          voicePrompt,
        });
      } catch (e) {
        const msg = e instanceof Error ? e.message : String(e);
        append({ role: 'error', text: msg });
        setBusy(false);
      }
    },
    [busy, sessionId, model, locale, append, projectKey],
  );

  const cancel = useCallback(async () => {
    try {
      await invoke('agent_cancel');
    } catch (e) {
      console.warn('[agent] cancel failed:', e);
    } finally {
      // Rust now emits run-ended synchronously on cancel; we also set busy
      // here to false to flip the UI instantly without depending on event
      // ordering.
      setBusy(false);
    }
  }, []);

  const approve = useCallback(async (approvalId: string, allow: boolean, reason?: string) => {
    setMessages(prev =>
      prev.map(m =>
        m.approvalId === approvalId ? { ...m, resolved: allow ? 'allow' : 'deny' } : m,
      ),
    );
    try {
      await invoke('agent_approve', { approvalId, allow, reason: reason ?? null });
    } catch (e) {
      console.warn('[agent] approve failed:', e);
    }
  }, []);

  const pick = useCallback(async (pickerId: string, optionId: string | null) => {
    // Lock the picker UI as soon as the user clicks (or cancels) so we
    // don't double-fire if they tap twice.
    setMessages(prev =>
      prev.map(m =>
        m.pickerId === pickerId ? { ...m, pickerChoice: optionId ?? '__cancelled__' } : m,
      ),
    );
    try {
      await invoke('agent_picker_result', { pickerId, optionId });
    } catch (e) {
      console.warn('[agent] pick failed:', e);
    }
  }, []);

  /// Adds a draft preview card to the chat. The bridge calls this after a
  /// generative import finishes (yt-dlp + analyse video, fetch article +
  /// gemini, classify pasted script, etc) — instead of overwriting the
  /// project blocks straight away, we surface the result inline and let
  /// the user decide.
  const proposeDraft = useCallback((draft: DraftPreview) => {
    // When a new draft of the same sourceUrl arrives, retire older
    // unresolved drafts so the user can only act on the latest version.
    // Without this, importing the same reel 3 times leaves 3 Apply
    // buttons live — applying an old one would overwrite the project
    // with a stale version.
    if (draft.sourceUrl) {
      setMessages(prev =>
        prev.map(m =>
          m.draft &&
          !m.draft.resolved &&
          m.draft.sourceUrl === draft.sourceUrl &&
          m.draft.draftId !== draft.draftId
            ? { ...m, draft: { ...m.draft, resolved: 'superseded' } }
            : m,
        ),
      );
    }
    append({
      role: 'system',
      text: '',
      draft,
    });
  }, [append]);

  /// Marks a draft as applied/discarded in the chat UI. The bridge calls
  /// this once it has acted on the user's button click.
  const resolveDraft = useCallback(
    (draftId: string, action: 'applied' | 'discarded') => {
      setMessages(prev =>
        prev.map(m =>
          m.draft?.draftId === draftId
            ? { ...m, draft: { ...m.draft, resolved: action } }
            : m,
        ),
      );
    },
    [],
  );

  /// Live-update a draft's block list when the agent iterates on it via
  /// regenerate_draft_block / replace_draft_block. The user sees the card
  /// rewrite itself in place instead of getting a second draft.
  const updateDraft = useCallback(
    (
      draftId: string,
      mutator: (
        blocks: Array<{ kind: 'avatar' | 'broll'; text: string }>,
      ) => Array<{ kind: 'avatar' | 'broll'; text: string }>,
    ) => {
      setMessages(prev =>
        prev.map(m => {
          if (m.draft?.draftId !== draftId) return m;
          return {
            ...m,
            draft: {
              ...m.draft,
              blocks: mutator(m.draft.blocks),
            },
          };
        }),
      );
    },
    [],
  );

  /// Add a setup card to the chat. The bridge calls this through the
  /// `__reelsAgent.requestSetup` shim and awaits the user's choice.
  const proposeSetup = useCallback((setup: SetupPrompt) => {
    append({
      role: 'system',
      text: '',
      setup,
    });
  }, [append]);

  /// Mark a setup card as resolved (submitted/skipped/cancelled) so the
  /// UI shows the locked state. The bridge handler also clears its local
  /// pending Promise via the shim.
  const resolveSetup = useCallback(
    (setupId: string, action: 'submitted' | 'skipped' | 'cancelled') => {
      setMessages(prev =>
        prev.map(m =>
          m.setup?.setupId === setupId
            ? { ...m, setup: { ...m.setup, resolved: action } }
            : m,
        ),
      );
    },
    [],
  );

  const proposeThumbnail = useCallback((dataUrl: string, filename: string) => {
    append({
      role: 'system',
      text: '',
      thumbnailDataUrl: dataUrl,
      thumbnailFilename: filename,
    });
  }, [append]);

  const clear = useCallback(() => {
    setMessages([]);
    setSessionId(null);
    deleteSessionFor(projectKey);
    streamMapRef.current.clear();
    toolMapRef.current.clear();
  }, [projectKey]);

  return {
    messages,
    busy,
    stale,
    send,
    cancel,
    approve,
    pick,
    proposeDraft,
    resolveDraft,
    updateDraft,
    proposeSetup,
    resolveSetup,
    proposeThumbnail,
    clear,
    sessionId,
    setSessionId,
    model,
    setModel,
  };
}
